<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Bower.Contracts/Bower.Contracts.csproj" />
    <ProjectReference Include="../Bower.Integrity/Bower.Integrity.csproj" />
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Bower.UnitTests" />
  </ItemGroup>
</Project>
