<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>bower</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifiers>win-x64;win-arm64;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Bower.Contracts/Bower.Contracts.csproj" />
    <ProjectReference Include="../Bower.Persistence/Bower.Persistence.csproj" />
    <ProjectReference Include="../Bower.PolicyEngine/Bower.PolicyEngine.csproj" />
  </ItemGroup>
</Project>
